### ISSUE TITLE
404 not found

### ISSUE THREAD

**Issue by chendaniely** [swcarpentry/website-archive#220]
Anyone else seeing this on the website?

![image](https://cloud.githubusercontent.com/assets/5782147/12860522/18639f2e-cc2b-11e5-8769-cf7d8ded4186.png)

**Comment by rachelss** [comment]
Yep

**Comment by pbanaszkiewicz** [comment]
Sorry, I broke the website. It will be back in about 15 minutes. Many apologies…

**Comment by pbanaszkiewicz** [comment]
@chendaniely @rachelss: the issue was fixed.

The reason for it was that #212 (which I provided) didn't update the "locked" dependency versions; I provided a new one in fe192cba95fc356fe61b01133e8a608bad0989f5.

Please let me know if everything's fine and I'll close this issue. Thanks for patience and once again - I'm sorry for the downtime.
