### ISSUE TITLE
Should we remove inactive instructors from the team page?

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/website-archive#280]

**Comment by jduckles** [comment]
I think so, do we have an "inactive" query cooked up? It would be nice to have a lightweight integration that just flips the bios to unpublished rather than deleting them.

Maybe we build the list of active instructors weekly or monthly from AMY, similar to how we build the calendar from AMY.

**Comment by maneesha** [comment]
I agree we should hide inactive instructors.  We should agree on how we're defining "inactive" -- it needs to be a function of when they were certified & how often they've taught.

Members are defined by having taught at least 2x in the past 730 days or having made a significant contribution to the work of SWC so we'd want to count those too.

**Comment by wking** [comment]
On Wed, Mar 02, 2016 at 07:19:22AM -0800, Jonah Duckles wrote:

> It would be nice to have a lightweight integration that just flips
> the bios to unpublished rather than deleting them.

Is this so the inactive list could be automatically pulled from AMY,
while keeping the bios in the website repository?  If the goal is to
go through periodically and adjust activity by hand, I'd recommend
just deleting bios (you can always pull them back out of version
control later) or moving them to a “previous contributors” section.

**Comment by jduckles** [comment]
@maneesha, shouldn't it just be the inverse of "members", if you're no longer qualified as a member you're inactive?

**Comment by maneesha** [comment]
@jduckles -- I would consider "active instructors" to be bigger than members. Members have taught at least 2x in the past 730 days.  I think "active instructors"  should include newly trained instructors who just haven't had a chance yet to teach, or maybe have only taught once.

That's why I think it should be a function of how often they've taught and when they got certified. I'm not sure what rules should apply there though.  So "inactive" is not just someone who's never taught -- it's someone who's never taught _and_ was certified more than X months ago.

**Comment by jduckles** [comment]
Ok, I agree, it is a union of the sets "members" and "recently badged". For some definition of recent, I'm inclined to use the same definition we're using for membership, I think it was two years.

**Comment by gvwilson** [comment]
We now have a discussion going on about this in the board's repo.
