### ISSUE TITLE
Word and PowerPoint "all wrong"?

### ISSUE THREAD

**Issue by jduckles** [swcarpentry/website-archive#371]
Moving discussion here from this thread: http://lists.software-carpentry.org/pipermail/discuss_lists.software-carpentry.org/2016-May/004337.html
'

**Comment by snacktavish** [comment]
There was a lot of discussion on list of use of Excel in academia. I mentioned this back and forth to an ecologist pal who asked "wait, how do they input their data?" Our examples use pre-existing data, but I don't know of other alternatives for getting from a handwritten field notebook to tabular data. So the argument "don't use excel" I think is intended to mean  don't use excel for statistical analyses, but it is valuable to consider that there is often going to be an excel or excel-like step in the process. Or are there alternatives that I don't know of? Plain text is not a fun way to input tabular data.
p.s. I'm glad this was taken off list - I'm much happier commenting when I don't feel like I'm spamming anyone!

**Comment by mikej888** [comment]
As the person who unleashed this monster thread, my intent was not to discuss the pros and cons of Excel, Word or PowerPoint but rather to highlight that statements that can be perceived as fundamentalist ("all wrong") or patronising ("training wheels") when commenting on researchers' existing tools or working practices can be very counter-productive and risk irritating or deterring them - an example of which was discussed in [2014](http://lists.software-carpentry.org/pipermail/discuss_lists.software-carpentry.org/2014-September/002125.html).

It may have been less painful if I'd remembered sooner about the [Tips for Instructors](http://swcarpentry.github.io/training-course/tips/) from Teaching Software Carpentry, particularly:

> Don’t insult your learners.
> Disparaging remarks about tools the learners are currently using may be meant humorously, but  are often taken as denigrating or insulting. For example, a lot of scientists have done a lot of first-rate research using Excel on Windows; telling them that this is somehow wrong will make them defensive, which will inhibit learning. Instead, talk positively about the benefits of the new approach that you’re > about to show them.

**Comment by SpacedGirl** [comment]
I'm of the same mind as 'snacktavish' about needing an excel like step [think in some ways R removes the need...trying to remember my very limited use of it] but not the case for other programs ie.python/fortran/matlab

Mike ---> think both your original purpose and what was discussed was rather substantial in nature and both discussions were informative for myself.

Think the painful part was in part  having an actual discussion rather than making apples to oranges comparisions. I personally find science related discussion really painful generally compared to discussions I have with others....both in and out of academia. [Not quite sure though]

**Comment by jttkim** [comment]
On Thu, May 05, 2016 at 08:05:14AM -0400, @gvwilson wrote:

> Thanks to everyone for their comments - I'm enjoying this thread,
> but I disagree with the "do it the hard way first" approach:

I absolutely agree that doing anything "the hard way" just for the heroics of it is unnecessary and often just stupid. Where I suggest to people to use techniques / systems they find hard is that I fear the way they perceive to be easier will turn out to be harder or even infeasible in the future.

> 1. Research tells us that people at all levels learn more, faster,
>    if they're given on-ramps rather than asked to climb cliffs - see
>    Sweller et al's work on cognitive load, which we discuss in
>    instructor training, or Vygotsky's zone of proximal development,
>    which we really ought to.

Yes -- breaking content into steps in a way that is well adapted to the pace of learners is essential, like breaking up code into classes and functions that are adequate. And it's one of those things that are tricky because the more experienced we are ourselves, the less we can use ourselves as a model of our learners (and jumping to conclusions based on using myself as a model is a mistake that I probably make on a daily basis).

One factor that makes it difficult (for me at least) to predict whether a step will be perceived as a cliff is that there's no objective measure of difficulty. Quite differently from physical steps / cliffs, the difficulty of taking a computational step continues to diminish each time we take it, until it's a thing we "_just_" do. And likewise, a major reason people find Excel and Word easy is that they used the stuff a lot. I'm still not sure how to reliably separate genuine learnability from the "I'm used to it" effect, and would appreciate discussion or references relevant to this matter. One candidate for an objective measure is the average number of operations required to carry out a task, particularly in a "Big-O" sense, e.g. processing _n_ files manually is _O_(_n_) while processing them with a shell script is _O_(1) -- is there any measure that applies this idea in a formal / systematic way?

> When we _do_ ask them to climb cliffs, it
> should be because we're teaching mountaineering, not because we're
> teaching botany and the wee shrub we want them to look at is twenty
> meters up a sheer rock face and what are you waiting for, lad, get
> on with it, we hardly ever have any actual fatalities as such in
> this leg of the field trip...  (That wasn't the best day of my
> academic life...)
> 1. Most of our learners are already pushing themselves as hard as
>    they can to master ecology, economics, or whatever else _they_ have
>    chosen to focus on.  When we say, "Here's some stuff you have to
>    wade through before you can do anything useful with a computer,"
>    we're prioritizing our interests over theirs.  We don't just use a
>    "most useful first" approach in our lessons because it's more
>    compelling than delayed gratification; we also use it because it's
>    more respectful.
> 2. And if people really _do_ have to wade through a bunch of stuff
>    before they get to what's useful, it's usually a sign that the
>    tool's designers didn't think about learnability.  Git's wildly
>    inconsistent command-line syntax is one example; Python's "if
>    **name** == '**main**'" is another, and, well, the list isn't a
>    short one.  Every time we ask our learners to wade, we should file a
>    high-priority bug report and figure out how to rearrange things so
>    they don't have to.  I mean, hell, we're trying to change the way
>    people do science: why not change the way they build software while
>    we're at it? :-)

**Comment by gvwilson** [comment]
Any action needed?

**Comment by mikej888** [comment]
@gvwilson, discussion seems to have fizzled out. If issues relating to the way in which the tools people used are referred to re-arise then the relevant bits of  http://swcarpentry.github.io/training-course/tips/ can be cited.

**Comment by SpacedGirl** [comment]
Pretty confused by @gvwilson 's question of action [saw this in an email] --> do you mean about high-volume channel or the other discussion above etc.?

I might be inclined to rejoin the discussion list if there are those wishing to discuss either rather than per usual SWF protocols of people shuffling issues to a garbage bin rather than acknowledging own thoughts.

To summarize, need to know what action to start/stop.

**Comment by jduckles** [comment]
Closing this issue as discussion has stalled.
