### ISSUE TITLE
Add the sell-novice-es and git-novice-es

### ISSUE THREAD

**Issue by rgaiacs** [swcarpentry/website-archive#867]
In https://github.com/swcarpentry/styles/issues/180, @orchid00 requested that https://github.com/Carpentries-ES/shell-novice and https://github.com/Carpentries-ES/git-novice be added to https://software-carpentry.org/lessons/.

# Requirements

- [ ] Introduce language at https://software-carpentry.org/lessons/.
- [ ] https://carpentries-es.github.io/shell-novice/ is in English.
- [ ] https://github.com/Carpentries-ES/shell-novice has a link to https://carpentries-es.github.io/shell-novice/_episodes_es which is broken.
- [ ] https://carpentries-es.github.io/git-novice/ is in English.
- [ ] https://github.com/Carpentries-ES/git-novice has http://swcarpentry.github.io/git-novice/ but it should be http://carpentries-es.github.io/git-novice/.

# Notes

@orchid00 wrote

> you will get an email from @ErinBecker or @map0logo or maybe @jduckles about rendering the translations from the shell and Git lessons to the carpentries repo.

**Comment by orchid00** [comment]
Huge thanks Ranier! @rgaiacs 

I have updated the links in the points you mentioned as requirements (3 and 5)
Yes the repos are in English, and the translations are in the folder episodes_es  respectively.

**Comment by rgaiacs** [comment]
> I have updated the links in the points you mentioned as requirements (3 and 5)

Thanks.

> the translations are in the folder episodes_es respectively.

I'm not sure if `_episodes_es` is the best place. How do you plan to sync the files in `_episodes` and `_episodes_es`? Probably a question for @map0logo

**Comment by agbeltran** [comment]
Hi all! I am not sure what was the plan, but I would think that we can move the translated episodes to ```_episodes``` (and remove ```_episodes_es```) so that we keep the same structure of the rest of the projects (allowing to see the lessons online without any other changes) and also we avoid that the English version of the episodes under``` _episodes``` gets outdated with respect to the original repositories. One thing we should add is the provenance of the repository, indicating in this case that it was translated from the English version of the same lesson (and we will do the same when we create lessons in Spanish and are then translated into English). What do you think?

**Comment by agbeltran** [comment]
BTW, the provenance information must keep the dates/versions of what was translated (to know if there were changes after that).

**Comment by raynamharris** [comment]
PR https://github.com/swcarpentry/website/pull/997 fixes this issue.

**Comment by weaverbel** [comment]
Can this issue be closed now? @orchid00 @raynamharris

**Comment by raynamharris** [comment]
Yes, all the Spanish lessons are on the website! Thanks @weaverbel
